replace-version

diff --git a/tomcat-8/maven-3.5/jdk-8/s2i/bin/assemble b/tomcat-8/maven-3.5/jdk-8/s2i/bin/assemble
--- a/tomcat-8/maven-3.5/jdk-8/s2i/bin/assemble
+++ b/tomcat-8/maven-3.5/jdk-8/s2i/bin/assemble
@@ -1,20 +1,6 @@
 #!/bin/bash
 
-# restore maven dependencies downloaded in a previous build,
-# so they do not have to be downloaded again.
-# /opt/s2i/destination/artifacts will only be present in the incremental build scenario
-# in which the target image name is an existing docker image which contains
-# dependencies from a prior build execution.
-function restore_saved_artifacts() {
-  if [ "$(ls -A /opt/s2i/destination/artifacts/ 2>/dev/null)" ]; then
-    echo -n " Restoring saved artifacts from prior build..."
-    mv /opt/s2i/destination/artifacts/.m2/repository $HOME/.m2
-  fi
-}
-
 CATALINA_HOME=${CATALINA_HOME:"/tomcat"}
-WAR_NAME=${WAR_NAME:="*.war"}
-VERSION=${VERSION:=""}
 
 # Source code provided to S2I is at ${HOME}
 LOCAL_SOURCE_DIR=${HOME}
@@ -28,6 +14,14 @@ ARTIFACT_DIR=${ARTIFACT_DIR:-target}
 DEPLOY_DIR=${CATALINA_HOME}/webapps
 mkdir -p ${DEPLOY_DIR}
 
+MAVEN_ARGS=${MAVEN_ARGS:=""}
+MAVEN_SETTINGS=${MAVEN_SETTINGS:=""}
+MAVEN_ARGS_APPEND=${MAVEN_ARGS_APPEND:=""}
+
+POM_PATH=${POM_PATH:"."}
+
+VERSION=${VERSION:=""}
+
 # Copy the source for compilation
 cp -Rf /opt/s2i/destination/src/. ${LOCAL_SOURCE_DIR}
 chgrp -R 0 ${LOCAL_SOURCE_DIR}
@@ -37,22 +31,9 @@ chmod -R g+rw ${LOCAL_SOURCE_DIR}
 # so run maven.
 if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
 
-  if [ -z "$INCREMENTAL" ]; then
-    export INCREMENTAL=true
-  fi
-
-  if [[ "$INCREMENTAL" = "true" ]]; then 
-    # restore any maven dependencies which will be present if this is an
-    # incremental build
-    echo -n "INCREMENTAL is set to $INCREMENTAL, we are restoring cached workspace containing .m2..."
-    restore_saved_artifacts
-    echo " restored"
-  fi
-
   pushd ${LOCAL_SOURCE_DIR}/${POM_PATH} &> /dev/null
 
   if [ -z "$MAVEN_ARGS" ]; then
-    #export MAVEN_ARGS="clean install -DskipTests"
     export MAVEN_ARGS="package -DskipTests"
   fi
 
@@ -75,10 +56,11 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
   if [ -n "$MAVEN_ARGS_APPEND" ]; then
     export MAVEN_ARGS="$MAVEN_ARGS $MAVEN_ARGS_APPEND"
   fi
+
   echo " Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
   # Replace version
-  if [ -z "$VERSION" ]; then
+  if [ ! -z "$VERSION" ]; then
     POM_FILE="./pom.xml"
 
     VER1="<version>[0-9a-zA-Z\.\-]\+<\/version>"
@@ -105,35 +87,34 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
   rm -rf ${DEPLOY_DIR}/*
   echo " cleaned up"
 
-  if [ ! -z `find -name ${WAR_NAME}` ]; then
-    echo "Moving built war file `find -name $WAR_NAME` into $DEPLOY_DIR for later deployment..."
-    mv `find -name ${WAR_NAME}` ${DEPLOY_DIR}/ROOT.war
-  else
-    echo "Aborting due to error : File not found, moving $WAR_NAME file, maybe it doesn't exist"
+  WAR_NAME=${WAR_NAME:="*.war"}
+  WAR_PATH=$(find -name ${WAR_NAME})
+
+  if [ ! -f ${WAR_PATH} ]; then
+    echo "Aborting due to error : File not found, moving $WAR_PATH file, maybe it doesn't exist"
     exit 1
   fi
 
-  if [[ "$INCREMENTAL" = "false" ]]; then
-    echo -n "INCREMENTAL is set to $INCREMENTAL, we are now cleaning image \"rm -rf . .m2\"..."
-    rm -rf ./* .m2
-    echo " cleaned up"
-  fi
+  echo "Moving built war file $WAR_PATH into $DEPLOY_DIR for later deployment..."
+  mv ${WAR_PATH} ${DEPLOY_DIR}/ROOT.war
 
   popd &> /dev/null
 
 else
 
-  echo "Moving binaries in source directory into $DEPLOY_DIR for later deployment..."
-  mv `find -name ${WAR_NAME}` ${DEPLOY_DIR}/ROOT.war
-  
-  ERR=$?
-  if [ ${ERR} -ne 0 ]; then
-    echo "Aborting due to error code $ERR from moving $WAR_NAME file, maybe it doesn't exist "
-    exit ${ERR}
+  WAR_NAME=${WAR_NAME:="*.war"}
+  WAR_PATH=$(find -name ${WAR_NAME})
+
+  if [ ! -f ${WAR_PATH} ]; then
+    echo "Aborting due to error : File not found, moving $WAR_PATH file, maybe it doesn't exist"
+    exit 1
   fi
+
+  echo "Moving built war file $WAR_PATH into $DEPLOY_DIR for later deployment..."
+  mv ${WAR_PATH} ${DEPLOY_DIR}/ROOT.war
 
 fi
 
 echo "...done"
 
-exit ${rc}
+exit 0
